---
- name: Local generation kubeconfigs..
  delegate_to: localhost
  run_once: true
  block:

  - name: Checking a local directory for configs..
    file:
      path: "{{ kubecfgdir }}"
      state: directory
      mode: '0700'


  - name: Generation kubeconfigs for cluster components..
    shell:
      cmd: >
        kubectl config set-cluster kubernetes-the-hard-way \
          --certificate-authority={{ pkidir }}/ca.pem \
          --embed-certs=true \
          --server=https://{{ master_node_addr }}:6443 \
          --kubeconfig={{ kubecfgdir }}/{{ item.component_name }}.kubeconfig &&

        kubectl config set-credentials {{ item.component_user }} \
          --client-certificate={{ pkidir }}/{{ item.component_name }}.pem \
          --client-key={{ pkidir }}/{{ item.component_name }}-key.pem \
          --embed-certs=true \
          --kubeconfig={{ kubecfgdir }}/{{ item.component_name }}.kubeconfig &&

        kubectl config set-context default \
          --cluster=kubernetes-the-hard-way \
          --user={{ item.component_user }} \
          --kubeconfig={{ kubecfgdir }}/{{ item.component_name }}.kubeconfig &&

        kubectl config use-context default --kubeconfig={{ kubecfgdir }}/{{ item.component_name }}.kubeconfig
      chdir: "{{ kubecfgdir }}"
      creates: "{{ item.component_name }}.kubeconfig"
    loop: 
      - { component_name: "kube-proxy", component_user: "system:kube-proxy" }
      - { component_name: "kube-controller-manager", component_user: "system:kube-controller-manager" }
      - { component_name: "kube-scheduler", component_user: "system:kube-scheduler" }
      - { component_name: "admin", component_user: "admin" }


  - name: Generation kubeconfigs for worker-nodes..
    shell:
      cmd: >
        kubectl config set-cluster kubernetes-the-hard-way \
          --certificate-authority={{ pkidir }}/ca.pem \
          --embed-certs=true \
          --server=https://{{ master_node_addr }}:6443 \
          --kubeconfig={{ kubecfgdir }}/{{ item }}.kubeconfig &&

        kubectl config set-credentials system:node:{{ item }} \
          --client-certificate={{ pkidir }}/{{ item }}.pem \
          --client-key={{ pkidir }}/{{ item }}-key.pem \
          --embed-certs=true \
          --kubeconfig={{ kubecfgdir }}/{{ item }}.kubeconfig &&

        kubectl config set-context default \
          --cluster=kubernetes-the-hard-way \
          --user=system:node:{{ item }} \
          --kubeconfig={{ kubecfgdir }}/{{ item }}.kubeconfig &&

        kubectl config use-context default --kubeconfig={{ kubecfgdir }}/{{ item }}.kubeconfig
      chdir: "{{ kubecfgdir }}"
      creates: "{{ item }}.kubeconfig"
    loop: "{{ groups['workers'] }}"