---
- name: Settings up local dns-resolver..
  when: inventory_hostname in groups['cluster_dns_resolver']
  block:

  - name: Checking the installation of dnsmasq..
    apt:
      name:
        - dnsmasq
      state: present
      update_cache: no


  - name: Disabling systemd-resolved service..
    systemd:
      name: systemd-resolved
      state: stopped
      enabled: no
      

  - name: Deleting configuration files..
    file: 
      path: "{{ item }}"
      state: absent
    loop:
      - "/etc/dnsmasq.conf"
      - "/etc/hosts"


  - name: Copy configuration files..
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - { src: "dnsmasq.conf.j2", dest: "/etc/dnsmasq.conf" }
      - { src: "hosts.j2", dest: "/etc/hosts" }


  - name: Enable dnsmasq service..
    systemd:
      name: dnsmasq
      state: restarted
      enabled: yes



- name: Settings up load balancer (masters > 1)..
  when: inventory_hostname in groups['cluster_dns_resolver'] and is_ha_cluster
  block:

  - name: Checking the installation of haproxy..
    apt:
      name: haproxy
      state: present
      update_cache: no


  - name: Copy haproxy.conf..
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    register: haproxy_config_updated


  - name: Enable haproxy service..
    systemd_service:
      name: haproxy
      state: restarted
      enabled: true
      daemon_reload: true
    when: haproxy_config_updated.changed